const types = {
	FETCH_SONGS: 'FETCH_SONGS',
    SWITCH_TILE_VIEW: 'SWITCH_TILE_VIEW',
    ADD_RECENT_SEARCH: 'ADD_RECENT_SEARCH',
    SET_SELECTED_RESULT:'SET_SELECTED_RESULT',
    SET_RECENT_SEARCH_TERMS:'SET_RECENT_SEARCH_TERMS'
};
export default types;
